geoblacklight:
  image: geoblacklight/geoblacklight
  ports:
    - "3000:3000"
  environment:
    RAILS_ENV: development
    SOLR_URL: http://solr:8983/solr/geoblacklight
  links:
    - solr

solr:
  image: geoblacklight/solr
  ports:
    - "8983:8983"
  volumes:
    - ./solr/:/opt/solr-5.2.1/
