version: '2'

services:
  geoblacklight:
    container_name: geoblacklight
    expose:
      - "3000"
    image: geoblacklight/geoblacklight
    environment:
      RAILS_ENV: development
      SOLR_URL: http://solr-gbl:8983/solr/geoblacklight
    depends_on:
      - solr-gbl
    labels:
      - "traefik.docker.network=thenetwork"
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.backend=geoblacklight"
      - "traefik.frontend.rule=Host:gbl-dev.scholarslab.org"
  solr-gbl:
    container_name: solr-gbl
    image: geoblacklight/solr
    expose:
      - "8983"
    volumes:
      - ./solr/:/opt/solr-5.2.1/
    labels:
      - "traefik.docker.network=thenetwork"
      - "traefik.enable=true"
      - "traefik.port=8983"
      - "traefik.backend=solr-gbl"
      - "traefik.frontend.rule=Host:gbl-dev.scholarslab.org; PathPrefix:/solr/"

networks:
  default:
    external:
      name: thenetwork